# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
destination: docs
title: Your awesome title
email: your-email@domain.com
disqus: ray-cheng
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

links:
    - { title: PHP, url: posts/php.html }
    - { title: Javascript, url: posts/javascript.html }
    - { title: JQuery, url: posts/jquery.html }
    - { title: Vuejs, url: posts/vuejs.html  }
    - { title: Docker, url: posts/docker.html  }
    - { title: Mysql, url: posts/mysql.html  }
    - { title: Mongodb, url: posts/mongodb.html  }
    - { title: 'Zend Framework 2', url: posts/zf2.html  }
    - { title: laravel, url: posts/laravel.html  }
    - { title: Git, url: posts/git.html  }
    - { title: System Skills, url: posts/system.html  }
    - { title: Redis, url: posts/redis.html  }
    - { title: Python, url: posts/python.html  }

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - resources

paginate: 10
paginate_path: "page:num"
  
